version: "3.9.1"
services:
  mongo-db:
    image: mongo
    ports:
      - 30001:27017
    expose:
      - 27017

    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ${PROJECT_DIR}/database:/data/db

  db-admin:
    image: mongo-express:latest
    restart: always
    ports:
      - "30000:8081"
    depends_on:
      - mongo-db

    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-db

  # redis:
  #   image: redis:latest
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./cache:/data

  backend-service:
    build:
      context: ./api
      dockerfile: Dockerfile
      #      target: prod
      target: dev # dev environment
    ports:
      - "8687:8686"
    restart: always

    depends_on:
      - mongo-db

    environment:
      PORT: 8686
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo-db/call_platform?authSource=admin
      AUTH_SALT_ROUND: 10
      AUTH_JWT_ACCESS_SECRET: bdf8061c8bb12486dc006e7f358c85cfacfc476ecc26e43ace6fca7a9fa9dd2a
      AUTH_ADMIN_JWT_ACCESS_EXPIRES_IN: 365d
      AUTH_JWT_REFRESH_SECRET: b644fdfc52d7eb4bbb5f46105f47baa3d53281526d926bca949ef9190bba0593
      AUTH_ADMIN_JWT_REFRESH_EXPIRES_IN: 720m
      OTP_EXPIRED_MINUTES: 10
      OTP_LENGTH: 4
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: gotutravel22@gmail.com
      MAIL_PASSWORD: ypyyausbeacnroal
      FALLBACK_LANGUAGE: en
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: 123456

    volumes:
      - ./api:/app
      - /app/node_modules

volumes:
  backend_service:
    driver: local
