version: "3.9.1"
services:
  mongo:
    image: mongo
    ports:
      - 30001:27017
    expose:
      - 27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: MONGO_INITDB_DATABASE

    volumes:
      - ${PROJECT_DIR}/gotu-database/data:/data/db

  redis:
    image: redis:latest
    profiles: [ "backend" ]
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data

  backend-service:
    profiles: [ "backend" ]
    build:
      context: ./api
      dockerfile: Dockerfile
      #      target: prod
      target: dev # dev environment
    ports:
      - "5000:8686"
    restart: always
    env_file:
      - .env

volumes:
  backend_service:
    driver: local
