-- AlterTable
ALTER TABLE `customer` ADD COLUMN `apple_id` VARCHAR(255) NULL,
    ADD COLUMN `facebook_id` VARCHAR(255) NULL,
    ADD COLUMN `google_id` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `notification_log` MODIFY `type` ENUM('TRANSACTION', 'SEND_TO_TOUR_GUIDE_SUBSCRIBE', 'BOOKING_TOUR', 'TOUR_GUIDE_APPLIED_CANCELED', 'TOUR_GUIDE_APPLIED', 'TOUR_GUIDE_MATCHED', 'BOOKING_VENDOR', 'VENDOR_CANCELED', 'VENDOR_CONFIRMED', 'OTHER') NOT NULL DEFAULT 'TRANSACTION';

-- AlterTable
ALTER TABLE `tour_guide` ADD COLUMN `apple_id` VARCHAR(255) NULL,
    ADD COLUMN `facebook_id` VARCHAR(255) NULL,
    ADD COLUMN `google_id` VARCHAR(255) NULL;

-- AlterTable
ALTER TABLE `vendor` ADD COLUMN `apple_id` VARCHAR(255) NULL,
    ADD COLUMN `facebook_id` VARCHAR(255) NULL,
    ADD COLUMN `google_id` VARCHAR(255) NULL;
