-- CreateTable
CREATE TABLE `HotDeal` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NULL,
    `banner_id` VARCHAR(191) NULL,
    `type` ENUM('GENERAL', 'HOME_BANNER_PAGE') NULL DEFAULT 'HOME_BANNER_PAGE',
    `status` ENUM('PUBLISH', 'DRAFT', 'DELETED') NOT NULL DEFAULT 'DRAFT',
    `description` VARCHAR(191) NULL,
    `banner_url` VARCHAR(191) NOT NULL,
    `deep_link_app` VARCHAR(191) NULL,
    `web_link` VARCHAR(191) NULL,
    `from` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `to` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
