-- AlterTable
ALTER TABLE `notification_log` MODIFY `type` ENUM('TRANSACTION', 'SEND_TO_TOUR_GUIDE_SUBSCRIBE', 'BOOKING_TOUR', 'TOUR_GUIDE_APPLIED_CANCELED', 'TOUR_GUIDE_APPLIED', 'TOUR_GUIDE_MATCHED', 'BOOKING_VENDOR', 'VENDOR_CANCELED', 'VENDOR_CONFIRMED', 'ADMIN_APPROVE_TOUR_GUIDE', 'OTHER') NOT NULL DEFAULT 'TRANSACTION';
