export const OtpAction = {
  USER_REGISTER: 'USER_REGISTER',
  CUSTOMER_REGISTER: 'CUSTOMER_REGISTER',
  VENDOR_REGISTER: 'VENDOR_REGISTER',
  TOUR_GUIDE_REGISTER: 'TOUR_GUIDE_REGISTER',
  USER_LOGIN: 'USER_LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
};
